#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import agent
import json

# Try to parse the stdin as JSON.
data = json.load(sys.stdin)
if data.get("lets_encrypt", False):
    cert_payload = {
        "fqdn": data["hostname"],
        "lets_encrypt": data["lets_encrypt"],
    }
    agent.set_certificate(cert_payload)
