#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import agent
import json
import os

# Check if action runs after import-module (ns7 migration tool):
migrating = os.getenv("AGENT_TASK_USER", "").startswith("ns7admin")

# Try to parse the stdin as JSON.
data = json.load(sys.stdin)
if "lets_encrypt" in data and not migrating:
    cert_payload = {
        "fqdn": data["hostname"],
        "lets_encrypt": data["lets_encrypt"],
    }
    agent.set_certificate(cert_payload)
