#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import agent
import json

# Try to parse the stdin as JSON.
data = json.load(sys.stdin)
if data.get("lets_encrypt", False):
    # on error, this function aborts the action:
    agent.set_default_certificate({
        "names": [data["hostname"]],
        "merge": True, # add hostname to existing certificate
    })
