#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

set -e

# get the hostname from the json file
/usr/bin/read -r hostname < <(jq -r '.hostname')

if [[ -z $EJABBERD_HOSTNAME ]];then
/usr/bin/echo "First configuration of Ejabberd FQDN" >&2
/usr/bin/exit 0
fi

if [[ $hostname == $EJABBERD_HOSTNAME ]];then
/usr/bin/echo "No need to modify Ejabberd FQDN" >&2
/usr/bin/exit 0
fi

/usr/bin/echo "We copy messages of old FQDN with new Ejabberd FQDN in MNESIA database" >&2

/usr/bin/podman exec ejabberd  bin/ejabberdctl dump /home/ejabberd/database/tmp_domain
#we sed the dump to the new FQDN
/usr/bin/podman exec ejabberd sed -i "s/${EJABBERD_HOSTNAME//./\\.}/${hostname//./\\.}/g" /home/ejabberd/database/tmp_domain
# All the old entries are preserved we just copy the previous messages to the new FQDN
# this allow to go back to the old FQDN if something goes wrong
# during the load, the old database is not erased, just new entries are added.
/usr/bin/podman exec ejabberd  bin/ejabberdctl load /home/ejabberd/database/tmp_domain

/usr/bin/echo "Ejabberd FQDN changed to $hostname" >&2

/usr/bin/podman exec ejabberd /usr/bin/rm -f /home/ejabberd/database/tmp_domain
