#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import json
import sys
import agent
import os

event = json.load(sys.stdin)

if str(event['node']) != os.environ['NODE_ID']:
    print(agent.SD_DEBUG + "Event ignored: source is another node")
    sys.exit(2)

if event['domain']['main'] != os.environ['EJABBERD_HOSTNAME']:
    print(agent.SD_DEBUG + "Event ignored: the certificate does not match our hostname")
    sys.exit(3)

if os.environ['TRAEFIK_LETS_ENCRYPT'] != 'True':
    print(agent.SD_DEBUG + "Event ignored: We do not require a LE certificate")
    sys.exit(4)
