#!/bin/bash

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

if systemctl --user -q is-active ejabberd; then
    # install-LE-certificate is triggered before start/reload
    systemctl --user -T try-reload-or-restart ejabberd
fi
