#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import agent
import json
import sys
import os

event = json.load(sys.stdin)
myname = os.environ["EJABBERD_HOSTNAME"]

if not agent.certificate_event_matches(event, myname):
    sys.exit(0) # ignore event if not relevant

# Obtain the changed certificate and its private key
get_proc = agent.run_helper(
    'get-certificate',
    '--cert-file=certificates/server.pem',
    '--key-file=certificates/server.key',
    myname,
)

# Reload the running service if the certificate differs
if get_proc.returncode == 0:
    agent.run_helper('systemctl', '--user', 'reload', 'ejabberd.service')
