#!/usr/bin/env python3

#
# Copyright (C) 2025 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#
import agent

# Unset the environment variable related to LE #7669 ns8-ejabberd:1.0.14
agent.unset_env("TRAEFIK_LETS_ENCRYPT")
