#!/usr/bin/env python3

#
# Copyright (C) 2022 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

#
# Read configuration
#

import os
import sys
import json
import agent
from agent.ldapproxy import Ldapproxy

# retrieve LDAP domains list
lp = Ldapproxy()
domains = []
for key in lp.get_domains_list():
    domains.append({
        "name": key,
        "label": key,
        "value": key,
    })

# Prepare return variable
config = {}

# Read current configuration from the environment file
config["hostname"] = os.getenv("EJABBERD_HOSTNAME","")
config["ldap_domain"] = os.getenv("EJABBERD_LDAP_DOMAIN",'')
config["adminsList"] = os.getenv("EJABBERD_ADMIN_LIST",'')
config["s2s"] = os.getenv("EJABBERD_S2S",'') == "True"
config["http_upload"] = os.getenv("EJABBERD_HTTP_UPLOAD",'') == "True"
config["mod_mam_status"] = os.getenv("EJABBERD_MOD_MAM_STATUS",'') == "True"
config["mod_http_upload_unlimited"] = os.getenv("EJABBERD_MOD_HTTP_UPLOAD_UNLIMITED",'') == "True"
config["shaper_normal"] = int(os.getenv("EJABBERD_SHAPER_NORMAL",500000))
config["shaper_fast"] = int(os.getenv("EJABBERD_SHAPER_FAST",1000000))
config['domains_list'] = domains
config["purge_mnesia_unlimited"] = os.getenv("EJABBERD_PURGE_MNESIA_UNLIMITED",'') == "True"
config["lets_encrypt"] = agent.get_certificate(os.getenv('EJABBERD_HOSTNAME')).get('type') == 'internal'
config["purge_mnesia_interval"] = int(os.getenv("EJABBERD_PURGE_MNESIA_INTERVAL",30))
config["purge_httpd_upload_interval"] = int(os.getenv("EJABBERD_PURGE_HTTPD_UPLOAD_INTERVAL",30))
config["webadmin"] = os.getenv("EJABBERD_WEBADMIN",'') == "True"

# Find the hostname of the node
config["fqdn"] = agent.get_hostname()

# Dump the configuration to stdout
json.dump(config, fp=sys.stdout)
