#!/usr/bin/env python3

#
# Copyright (C) 2023 Nethesis S.r.l.
# SPDX-License-Identifier: GPL-3.0-or-later
#

import sys
import json
import agent

request = json.load(sys.stdin)

original_environment = request['environment']

for evar in [
    "EJABBERD_HOSTNAME",
    "EJABBERD_LDAP_DOMAIN",
    "EJABBERD_ADMIN_LIST",
    "EJABBERD_HTTP_UPLOAD",
    "EJABBERD_MOD_MAM_STATUS",
    "EJABBERD_SHAPER_NORMAL",
    "EJABBERD_SHAPER_FAST",
    "EJABBERD_MOD_HTTP_UPLOAD_QUOTA_STATUS",
    "EJABBERD_PURGE_MNESIA",
    "EJABBERD_PURGE_MNESIA_INTERVAL",
    "TRAEFIK_LETS_ENCRYPT",
    ]:
     agent.set_env(evar, original_environment[evar])
