name: "Build API JSON Schema docs"

on:
  push:
    paths:
      - '**/validate-input.json'
      - '**/validate-output.json'
      - '**/validator-definitions.json'
    branches-ignore:
      - 'renovate/**'
    tags:
      - "**"

jobs:
  build-apidoc:
    uses: NethServer/ns8-github-actions/.github/workflows/build-apidoc.yml@v1
